project:
  type: website

website:
  title: "Laboratório Aberto"
  description: "Um blog de estudos em ciência de dados e IA"
  site-url: "https://terezalacerda.github.io/laboratorio-aberto"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: journal
    css: styles.css



